/**
 * dsh-client-ui-password-generator — browser half (client).
 *
 * Registers a "密码生成器" entry into the `sidebar.footer.action` list slot
 * (beside Settings) and renders a small modal with four complexity tiers:
 *   低 / 中 / 高  — generated locally with `crypto.getRandomValues`;
 *   🎲 (有意义)   — generated by the host half through `ctx.llm`, streamed
 *                   over the existing Remote channel; API key never leaves
 *                   the host process (plan §4.5, path ①).
 *
 * No history: no localStorage / IndexedDB / settings / session writes. The
 * password lives only in React state inside the modal and is destroyed the
 * moment the modal closes (the component unmounts).
 *
 * Build contract: this file is the BODY of the lazy-CJS factory emitted by
 * `scripts/build.mjs`. Two locals are provided by the wrapper:
 *   _react      — require("react")
 *   _primitives — require("@deepseek-ai/dsh-client-ui-primitives")
 * No JSX / TypeScript — plain React.createElement.
 */

const React = _react;
const { Button, Modal, Toast, writeClipboard } = _primitives;

/* ── locale namespace & dictionaries (zh is the key-set source of truth) ── */
const NS = "ui-password-generator";

const zh = {
  "entry.label": "密码生成器",
  "entry.title": "打开密码生成器",
  "modal.title": "密码生成器",
  "modal.close": "关闭",
  "seg.low": "低",
  "seg.mid": "中",
  "seg.high": "高",
  "seg.smart.title": "有意义密码（AI 生成）",
  "pw.placeholder": "点击下方按钮生成",
  "pw.copy": "复制",
  "pw.copied": "已复制 ✓",
  "strength.weak": "弱",
  "strength.mid": "中",
  "strength.strong": "强",
  "gen.run": "生成",
  "gen.dice": "🎲 生成",
  "gen.running": "生成中…",
  "gen.error": "生成失败，请重试",
  "source.label": "基于 Agent 生成 · 非纯随机，便于记忆",
  "privacy.line": "不保存任何历史 · 只在内存生成，关闭即销毁，无存储、无记录",
  "toast.copied": "已复制到剪贴板",
  "toast.copyFailed": "复制失败：剪贴板不可用",
  "toast.closed": "已关闭 · 密码已从内存销毁",
};

const en = {
  "entry.label": "Password Generator",
  "entry.title": "Open password generator",
  "modal.title": "Password Generator",
  "modal.close": "Close",
  "seg.low": "Low",
  "seg.mid": "Medium",
  "seg.high": "High",
  "seg.smart.title": "Meaningful password (AI)",
  "pw.placeholder": "Click Generate below",
  "pw.copy": "Copy",
  "pw.copied": "Copied ✓",
  "strength.weak": "Weak",
  "strength.mid": "Medium",
  "strength.strong": "Strong",
  "gen.run": "Generate",
  "gen.dice": "🎲 Generate",
  "gen.running": "Generating…",
  "gen.error": "Generation failed, try again",
  "source.label": "Agent-generated · not purely random, easy to remember",
  "privacy.line": "No history is saved · generated in memory only, destroyed on close — no storage, no records",
  "toast.copied": "Copied to clipboard",
  "toast.copyFailed": "Copy failed: clipboard unavailable",
  "toast.closed": "Closed · password destroyed in memory",
};

/* ── Remote contribution for the host `passwordGenerator` service ──
 * Mirrors the host gateway's SRC-derived descriptor (src-json would be
 * rejected by the client mount, which demands strict codecs), so a tiny
 * pass-through schema stands in for the generated zod codec.
 */
const passThroughSchema = {
  parse(value) {
    return value;
  },
};

const TYPERT_REMOTE = {
  package: "dsh-client-ui-password-generator",
  descriptors: [
    {
      id: "dsh-client-ui-password-generator#passwordGenerator/generateMeaningful",
      service: "passwordGenerator",
      namespace: "passwordGenerator",
      method: "generateMeaningful",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "request",
          wire: "request",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "dsh-client-ui-password-generator#generateMeaningful:request",
            schema: passThroughSchema,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "dsh-client-ui-password-generator#generateMeaningful:result",
        schema: passThroughSchema,
      },
      sourceLocation: { file: "src/client/index.js", line: 1, column: 1 },
    },
  ],
};

/* ── complexity tiers & character sets (0O1lI removed) ── */
const CONFIGS = {
  low: { length: 8, sets: ["lower", "digit"] },
  mid: { length: 12, sets: ["lower", "upper", "digit"] },
  high: { length: 16, sets: ["lower", "upper", "digit", "symbol"] },
};

const SETS = {
  lower: "abcdefghjkmnpqrstuvwxyz",
  upper: "ABCDEFGHJKMNPQRSTUVWXYZ",
  digit: "23456789",
  symbol: "!@#$%^&*()-_=+[]{};:,.<>?",
};

/* ── cryptographically secure randomness (rejection sampling, no bias) ── */
function secureRandomInt(maxExclusive) {
  if (maxExclusive <= 0) throw new Error("bad range");
  const range = Math.floor(0x100000000 / maxExclusive) * maxExclusive;
  const buf = new Uint32Array(1);
  let x;
  do {
    crypto.getRandomValues(buf);
    x = buf[0];
  } while (x >= range);
  return x % maxExclusive;
}

const pickChar = (set) => set[secureRandomInt(set.length)];

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = secureRandomInt(i + 1);
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** Generate one random password for the low/mid/high tiers (guaranteed class coverage). */
function generate(level) {
  const cfg = CONFIGS[level];
  const pool = cfg.sets.map((setName) => SETS[setName]).join("");
  const chars = cfg.sets.map((setName) => pickChar(SETS[setName]));
  while (chars.length < cfg.length) chars.push(pickChar(pool));
  return shuffle(chars).join("");
}

/* ── entropy estimate: length × log2(character-set size) ── */
function entropyBits(level) {
  const cfg = level === "smart" ? CONFIGS.high : CONFIGS[level];
  const poolSize = cfg.sets.reduce((sum, setName) => sum + SETS[setName].length, 0);
  return Math.round(cfg.length * Math.log2(poolSize));
}

function strengthOf(bits) {
  if (bits < 50) return { labelKey: "strength.weak", color: "var(--dsw-alias-state-error-primary)", pct: 30 };
  if (bits < 80) return { labelKey: "strength.mid", color: "var(--dsw-alias-state-warn-primary)", pct: 65 };
  return { labelKey: "strength.strong", color: "var(--dsw-alias-state-success-primary)", pct: 100 };
}

/* ── dice face (3×3 grid, values 1–6) ── */
const DICE_FACES = {
  1: [[1, 1]],
  2: [[0, 0], [2, 2]],
  3: [[0, 0], [1, 1], [2, 2]],
  4: [[0, 0], [0, 2], [2, 0], [2, 2]],
  5: [[0, 0], [0, 2], [1, 1], [2, 0], [2, 2]],
  6: [[0, 0], [0, 2], [1, 0], [1, 2], [2, 0], [2, 2]],
};
const DICE_GRID = [6.5, 12, 17.5];

function DiceFace({ face, className }) {
  return React.createElement(
    "svg",
    { viewBox: "0 0 24 24", className, "aria-hidden": true },
    React.createElement("rect", { x: 1.2, y: 1.2, width: 21.6, height: 21.6, rx: 5.4, className: "pgw-diceFace" }),
    DICE_FACES[face].map(([row, col], index) =>
      React.createElement("circle", { key: index, cx: DICE_GRID[col], cy: DICE_GRID[row], r: 2.3, className: "pgw-diceDot" }),
    ),
  );
}

/* ── styles (DSW theme tokens; tag id dedupes like the shipped bundles) ── */
const CSS_TAG_ID = "dsh-client-ui-password-generator/password-generator.css";
const CSS = [
  ".pgw-trigger{box-sizing:border-box;cursor:pointer;width:calc(100% + 8px);height:34px;color:var(--dsw-alias-label-primary);background:0 0;border:none;border-radius:12px;flex:none;align-items:center;gap:8px;margin:4px -4px;padding:6px 2px 6px 10px;font-family:inherit;font-size:14px;line-height:22px;display:flex;overflow:hidden}",
  ".pgw-trigger:hover{background:var(--dsw-alias-interactive-bg-hover)}",
  ".pgw-trigger.pgw-rail{border-radius:50%;justify-content:center;gap:0;width:36px;height:36px;margin:8px 0 10px;padding:0}",
  ".pgw-triggerLabel{white-space:nowrap;overflow:hidden}",
  ".pgw-key{font-size:15px;line-height:1;flex:none}",
  ".pgw-dialog{width:420px;max-width:calc(100vw - 48px)}",
  ".pgw-body{display:flex;flex-direction:column;gap:14px}",
  ".pgw-seg{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;background:var(--dsw-alias-bg-layer-3);border-radius:12px;padding:5px}",
  ".pgw-segBtn{border:none;background:0 0;color:var(--dsw-alias-label-tertiary);font-family:inherit;font-size:13px;padding:8px 0;border-radius:8px;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:5px;transition:background .1s,color .1s}",
  ".pgw-segBtn:hover{color:var(--dsw-alias-label-primary)}",
  ".pgw-segBtn.pgw-on{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);box-shadow:var(--dsw-shadow-lv1);font-weight:500}",
  ".pgw-segBtn.pgw-on.pgw-onLow{color:var(--dsw-alias-state-success-primary)}",
  ".pgw-segBtn.pgw-on.pgw-onMid{color:var(--dsw-alias-state-warn-primary)}",
  ".pgw-segBtn.pgw-on.pgw-onHigh{color:var(--dsw-alias-brand-primary)}",
  ".pgw-segBtn.pgw-on.pgw-onSmart{color:var(--dsw-alias-brand-primary)}",
  ".pgw-miniDice{width:16px;height:16px;flex:none}",
  ".pgw-diceFace{fill:var(--dsw-alias-label-primary)}",
  ".pgw-diceDot{fill:var(--dsw-alias-bg-base)}",
  ".pgw-segBtn.pgw-rolling .pgw-miniDice{animation:pgw-dice-roll .9s cubic-bezier(.3,.4,.4,1)}",
  "@keyframes pgw-dice-roll{0%{transform:rotate(0) translateY(0)}25%{transform:rotate(150deg) translateY(-3px)}50%{transform:rotate(300deg) translateY(0)}75%{transform:rotate(450deg) translateY(-2px)}100%{transform:rotate(540deg) translateY(0)}}",
  ".pgw-pwBox{background:var(--dsw-specific-input-major);border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:12px 14px;min-height:48px;display:flex;align-items:center;justify-content:space-between;gap:12px}",
  ".pgw-pwText{font-family:var(--dsw-font-mono);font-size:15px;letter-spacing:.5px;word-break:break-all;color:var(--dsw-alias-label-primary);line-height:1.4;min-width:0}",
  ".pgw-pwText.pgw-placeholder{color:var(--dsw-alias-label-tertiary);font-family:var(--dsw-font-family);font-size:13px}",
  ".pgw-pwText.pgw-new{animation:pgw-pw-in .25s ease-out}",
  "@keyframes pgw-pw-in{from{opacity:0;transform:translateY(3px)}to{opacity:1;transform:none}}",
  ".pgw-source{font-size:12px;color:var(--dsw-alias-label-caption);display:flex;align-items:center;gap:6px;line-height:1.5}",
  ".pgw-source .pgw-sourceText{min-width:0;word-break:break-word}",
  ".pgw-sourceDice{width:13px;height:13px;flex:none}",
  ".pgw-strength{display:flex;align-items:center;gap:10px}",
  ".pgw-strengthBar{flex:1;height:4px;background:var(--dsw-alias-bg-layer-3);border-radius:2px;overflow:hidden}",
  ".pgw-strengthFill{height:100%;width:0;border-radius:2px;transition:width .25s,background .25s}",
  ".pgw-strengthLabel{font-size:11.5px;color:var(--dsw-alias-label-caption);min-width:52px;text-align:right;font-variant-numeric:tabular-nums}",
  ".pgw-privacy{font-size:11.5px;color:var(--dsw-alias-label-caption);line-height:1.6;display:flex;gap:6px;align-items:flex-start}",
  ".pgw-privacy .pgw-shield{color:var(--dsw-alias-state-success-primary);flex:none;margin-top:1px}",
  ".pgw-genBtn{width:100%;justify-content:center}",
].join("");

if (typeof document !== "undefined" && document.querySelector(`style[data-plugin-css=${JSON.stringify(CSS_TAG_ID)}]`) === null) {
  const tag = document.createElement("style");
  tag.dataset.plugin = "dsh-client-ui-password-generator";
  tag.dataset.pluginCss = CSS_TAG_ID;
  tag.textContent = CSS;
  document.head.appendChild(tag);
}

/* ── modal body ── */
function PasswordGeneratorModal({ t, generateMeaningful, onClose, showToast }) {
  const [level, setLevel] = React.useState("mid");
  const [password, setPassword] = React.useState(null); // { text, note } | null
  const [generating, setGenerating] = React.useState(false);
  const [rolling, setRolling] = React.useState(false);
  const [diceFace, setDiceFace] = React.useState(5);
  const [copied, setCopied] = React.useState(false);
  const runSeq = React.useRef(0);
  const rollTimer = React.useRef(null);

  // Unmount (modal close) must stop the dice ticker no matter what is in flight.
  React.useEffect(
    () => () => {
      if (rollTimer.current !== null) clearInterval(rollTimer.current);
    },
    [],
  );

  const clearPassword = React.useCallback(() => {
    runSeq.current += 1; // invalidate any in-flight smart generation
    if (rollTimer.current !== null) {
      clearInterval(rollTimer.current);
      rollTimer.current = null;
    }
    setPassword(null);
    setCopied(false);
    setRolling(false);
    setGenerating(false);
  }, []);

  const switchLevel = React.useCallback(
    (next) => {
      if (next === level) return;
      setLevel(next);
      clearPassword();
    },
    [level, clearPassword],
  );

  const copyPassword = React.useCallback(async () => {
    if (password === null) return;
    const ok = await writeClipboard(password.text);
    if (ok) {
      setCopied(true);
      showToast(t("toast.copied"));
    } else {
      showToast(t("toast.copyFailed"));
    }
  }, [password, showToast, t]);

  const generateNew = React.useCallback(async () => {
    if (generating) return;
    if (level !== "smart") {
      setPassword({ text: generate(level), note: null });
      setCopied(false);
      return;
    }
    const seq = runSeq.current + 1;
    runSeq.current = seq;
    setGenerating(true);
    setRolling(true);
    setPassword(null);
    setCopied(false);
    const timer = setInterval(() => setDiceFace(1 + secureRandomInt(6)), 200);
    rollTimer.current = timer;
    const minDelayMs = 900 + secureRandomInt(500);
    const started = Date.now();
    let answer = null;
    let errorMsg = null;
    try {
      answer = await generateMeaningful({ length: 16 });
    } catch (error) {
      errorMsg = error instanceof Error ? error.message : String(error);
    }
    const elapsed = Date.now() - started;
    if (elapsed < minDelayMs) await new Promise((resolve) => setTimeout(resolve, minDelayMs - elapsed));
    if (rollTimer.current === timer) rollTimer.current = null;
    clearInterval(timer);
    setDiceFace(1 + secureRandomInt(6));
    if (runSeq.current !== seq) return; // a switch/close happened meanwhile — drop the result
    setRolling(false);
    setGenerating(false);
    if (answer !== null && typeof answer.password === "string" && answer.password.length > 0) {
      setPassword({ text: answer.password, note: answer.note ?? "" });
    } else {
      showToast(errorMsg ? `${t("gen.error")} · ${errorMsg}` : t("gen.error"));
      if (errorMsg) console.error("[password-generator] generateMeaningful failed:", errorMsg);
    }
  }, [generating, level, generateMeaningful, showToast, t]);

  const strength = password !== null ? strengthOf(entropyBits(level)) : null;
  const isSmart = level === "smart";

  return React.createElement(
    Modal,
    {
      open: true,
      onClose,
      title: t("modal.title"),
      closeLabel: t("modal.close"),
      className: "pgw-dialog",
      footer: React.createElement(
        Button,
        {
          variant: "primary",
          className: "pgw-genBtn",
          disabled: generating,
          onClick: generateNew,
        },
        generating
          ? t("gen.running")
          : isSmart
            ? t("gen.dice")
            : t("gen.run"),
      ),
    },
    React.createElement(
      "div",
      { className: "pgw-body" },
      React.createElement("div", { className: "pgw-seg", role: "group", "aria-label": t("modal.title") },
        ["low", "mid", "high", "smart"].map((key) =>
          React.createElement(
            "button",
            {
              key,
              type: "button",
              className: [
                "pgw-segBtn",
                level === key ? "pgw-on" : "",
                level === key ? `pgw-on${key[0].toUpperCase()}${key.slice(1)}` : "",
                key === "smart" && rolling ? "pgw-rolling" : "",
              ].filter(Boolean).join(" "),
              title: key === "smart" ? t("seg.smart.title") : undefined,
              "data-level": key,
              onClick: () => switchLevel(key),
              disabled: generating,
            },
            key === "smart"
              ? React.createElement(DiceFace, { face: diceFace, className: "pgw-miniDice" })
              : t(`seg.${key}`),
          ),
        ),
      ),
      React.createElement("div", { className: "pgw-pwBox" },
        React.createElement("span", { className: password === null ? "pgw-pwText pgw-placeholder" : "pgw-pwText" },
          password === null ? t("pw.placeholder") : password.text,
        ),
        React.createElement(
          Button,
          {
            variant: "ghost",
            size: "sm",
            disabled: password === null || generating,
            onClick: copyPassword,
            className: copied ? "pgw-copied" : undefined,
          },
          copied ? t("pw.copied") : t("pw.copy"),
        ),
      ),
      isSmart &&
        React.createElement("div", { className: "pgw-source" },
          React.createElement(DiceFace, { face: 5, className: "pgw-sourceDice" }),
          React.createElement("span", { className: "pgw-sourceText" }, password !== null && password.note ? password.note : t("source.label")),
        ),
      React.createElement("div", { className: "pgw-strength" },
        React.createElement("div", { className: "pgw-strengthBar" },
          React.createElement("div", {
            className: "pgw-strengthFill",
            style: strength === null ? undefined : { width: `${strength.pct}%`, background: strength.color },
          }),
        ),
        React.createElement("span", { className: "pgw-strengthLabel" },
          strength === null ? "—" : `${t(strength.labelKey)} · ${entropyBits(level)} bit`,
        ),
      ),
      React.createElement("div", { className: "pgw-privacy" },
        React.createElement("span", { className: "pgw-shield" }, "🛡"),
        React.createElement("span", null, t("privacy.line")),
      ),
    ),
  );
}

/* ── sidebar footer action entry: trigger + modal + toast ── */
function PasswordGeneratorEntry(props) {
  const { wide, t, generateMeaningful } = props;
  const [open, setOpen] = React.useState(false);
  const [toast, setToast] = React.useState(null); // { text, seq }

  const showToast = React.useCallback((text) => {
    setToast({ text, seq: Date.now() });
  }, []);

  const close = React.useCallback(() => {
    setOpen(false);
    showToast(t("toast.closed"));
  }, [t, showToast]);

  return React.createElement(
    React.Fragment,
    null,
    React.createElement(
      "button",
      {
        type: "button",
        className: wide ? "pgw-trigger" : "pgw-trigger pgw-rail",
        "aria-haspopup": "dialog",
        "aria-expanded": open,
        title: t("entry.title"),
        onClick: () => setOpen(true),
      },
      React.createElement("span", { className: "pgw-key", "aria-hidden": true }, "🔑"),
      wide ? React.createElement("span", { className: "pgw-triggerLabel" }, t("entry.label")) : null,
    ),
    open
      ? React.createElement(PasswordGeneratorModal, { t, generateMeaningful, onClose: close, showToast })
      : null,
    toast !== null
      ? React.createElement(Toast, {
          key: toast.seq,
          text: toast.text,
          onDone: () => setToast(null),
        })
      : null,
  );
}

/* ── plugin entry ── */
const inject = ["slots", "locale", "remote"];

async function apply(ctx) {
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), "ui-password-generator: dictionaries");
  await ctx.remote.$mount(TYPERT_REMOTE);
  // `remote.passwordGenerator` is a cordis service with a dotted name. The
  // traced ctx proxy resolves `ctx.remote.passwordGenerator` through the
  // context, which demands the name be in the `inject` list — but injecting it
  // would deadlock (this plugin mounts it itself in `apply`). `ctx.get(name)`
  // performs the lookup without that gate, so capture the namespace here.
  const passwordGenerator = ctx.get("remote.passwordGenerator");
  ctx.slots.inject("sidebar.footer.action", () =>
    ctx.slots.register(
      {
        name: "sidebar.footer.action",
        id: "password-generator",
        order: 110,
        label: "密码生成器",
        locale: NS,
        inject: () => ({
          generateMeaningful: async (request) => {
            // Belt-and-suspenders client-side bound; the host normally resolves
            // within its own 20s LLM timeout, but this guarantees the UI never
            // hangs on "生成中…" if the carrier stalls.
            const answered = await Promise.race([
              passwordGenerator.generateMeaningful(request),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error("生成请求超时")), 25000),
              ),
            ]);
            if (!answered.ok) throw new Error(`${answered.error.code}: ${answered.error.message}`);
            return answered.value;
          },
        }),
      },
      PasswordGeneratorEntry,
    ),
  );
}

exports.apply = apply;
exports.inject = inject;
